version: '2.0'

services:
  node:
    image: node
    container_name: node
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "yarn && yarn run watch"

  php7:
    image: adiwitcoth/php
    container_name: php7
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      # - ~/.composer:/root/.composer
      # - ~/.ssh:/root/.ssh
    command: bash -c "composer install && php -r \"file_exists('.env') || copy('.env.example', '.env');\" && php -r \"strpos(file_get_contents('.env'), 'APP_KEY=base64:') || include('artisan');\" key:generate && php artisan migrate && php -v && php -S 0.0.0.0:80 -t public"
    depends_on:
      - mariadb

  mariadb:
    image: mariadb
    container_name: mariadb
    environment:
      MYSQL_DATABASE: "adiwitcoth"
      MYSQL_ROOT_PASSWORD: "88888888"
    # volumes:
      # - ~/Code/adiwitcoth/_database:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8888:80"
    depends_on:
      - mariadb
    links:
      - mariadb:db
